# Generated by Django 4.1.6 on 2023-04-28 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_created_at_remove_item_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
